test_fib: test_fib.cc fib.cc fib.hh
	g++ -o test_fib test_fib.cc fib.cc
test_fib2: test_fib2.cc fib.cc
	g++ -o test_fib2 test_fib2.cc fib.cc
test_mat: test_mat.cc
	g++ -o test_mat test_mat.cc 
test_arr: arr_test.cc
	g++ -o test_arr arr_test.cc