fib: fib.cc
	g++ -o test_fib fib.cc
binsearch: bin_search.cc arr.hh
	g++ -o test_binsearch bin_search.cc
exchange: exchange_sort.cc arr.hh
	g++ -o test_exchange exchange_sort.cc
test_sum: sum.cc arr.hh
	g++ -o test_sum sum.cc
exchange: exchange_sort.cc arr.hh
	g++ -o test_exchange exchange_sort.cc
test_seqsearch: seq_search.cc
	g++ -o test_seqsearch seq_search.cc